name: KenSnyder.io
favicon: null
layout_spectrum: 0.1313648649957031
typography_spectrum: 0.6225537681020796
title: KenSnyder.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4924696418456733
  lightness: 0.2639886129181832
  saturation: 0.6417087777517736
  rhythmicContrast: 0.07460907916538417
purpose: []
